
delivery_car: # robot name space

  gazebo_ros_control/pid_gains:

    left_rear_wheel_joint: {p: 100, i: 0.1, d: 10.0}
    right_rear_wheel_joint: {p: 100, i: 0.1, d: 10.0}
    left_front_turn_joint: {p: 100, i: 0.1, d: 10.0}
    right_front_turn_joint: {p: 100, i: 0.1, d: 10.0}